-- Hotel Management System Database Setup

-- Create sequences
CREATE SEQUENCE ROOM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE GUEST_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BOOKING_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PAYMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;

-- Create tables
CREATE TABLE ROOMS (
    ID NUMBER(19) PRIMARY KEY,
    ROOM_NUMBER VARCHAR2(20) NOT NULL UNIQUE,
    ROOM_TYPE VARCHAR2(50) NOT NULL,
    PRICE_PER_NIGHT NUMBER(10,2) NOT NULL,
    CAPACITY NUMBER(10) NOT NULL,
    AVAILABLE CHAR(1) DEFAULT '1',
    DESCRIPTION VARCHAR2(1000),
    FLOOR_NUMBER NUMBER(10),
    HAS_VIEW CHAR(1) DEFAULT '0',
    HAS_WIFI CHAR(1) DEFAULT '1',
    HAS_AC CHAR(1) DEFAULT '1',
    HAS_TV CHAR(1) DEFAULT '1',
    IMAGE_URL VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GUESTS (
    ID NUMBER(19) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(500),
    CITY VARCHAR2(100),
    COUNTRY VARCHAR2(100),
    POSTAL_CODE VARCHAR2(20),
    DATE_OF_BIRTH DATE,
    ID_CARD_NUMBER VARCHAR2(50),
    EMERGENCY_CONTACT_NAME VARCHAR2(100),
    EMERGENCY_CONTACT_PHONE VARCHAR2(20),
    SPECIAL_REQUIREMENTS VARCHAR2(1000),
    IS_VIP CHAR(1) DEFAULT '0',
    TOTAL_STAYS NUMBER(10) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BOOKINGS (
    ID NUMBER(19) PRIMARY KEY,
    GUEST_ID NUMBER(19) NOT NULL,
    ROOM_ID NUMBER(19) NOT NULL,
    CHECK_IN_DATE DATE NOT NULL,
    CHECK_OUT_DATE DATE NOT NULL,
    NUMBER_OF_GUESTS NUMBER(10) NOT NULL,
    BOOKING_STATUS VARCHAR2(20) NOT NULL,
    PAYMENT_STATUS VARCHAR2(20),
    BOOKING_DATE DATE DEFAULT SYSDATE,
    TOTAL_PRICE NUMBER(10,2),
    SPECIAL_REQUESTS VARCHAR2(1000),
    CHECKED_IN_AT TIMESTAMP,
    CHECKED_OUT_AT TIMESTAMP,
    CANCELLATION_REASON VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BOOKING_GUEST FOREIGN KEY (GUEST_ID) REFERENCES GUESTS(ID),
    CONSTRAINT FK_BOOKING_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID)
);

CREATE TABLE PAYMENTS (
    ID NUMBER(19) PRIMARY KEY,
    BOOKING_ID NUMBER(19) NOT NULL,
    AMOUNT NUMBER(10,2) NOT NULL,
    PAYMENT_METHOD VARCHAR2(50) NOT NULL,
    PAYMENT_STATUS VARCHAR2(20) NOT NULL,
    TRANSACTION_ID VARCHAR2(100),
    PAYMENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CARD_LAST_FOUR VARCHAR2(4),
    BILLING_ADDRESS VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PAYMENT_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES BOOKINGS(ID)
);

CREATE TABLE USERS (
    ID NUMBER(19) PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    PHONE_NUMBER VARCHAR2(20),
    ENABLED CHAR(1) DEFAULT '1',
    ACCOUNT_NON_LOCKED CHAR(1) DEFAULT '1',
    ACCOUNT_NON_EXPIRED CHAR(1) DEFAULT '1',
    CREDENTIALS_NON_EXPIRED CHAR(1) DEFAULT '1',
    LAST_LOGIN TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USER_ROLES (
    USER_ID NUMBER(19) NOT NULL,
    ROLE VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ID, ROLE)
);

-- Create indexes
CREATE INDEX IDX_ROOM_AVAILABLE ON ROOMS(AVAILABLE);
CREATE INDEX IDX_ROOM_TYPE ON ROOMS(ROOM_TYPE);
CREATE INDEX IDX_GUEST_EMAIL ON GUESTS(EMAIL);
CREATE INDEX IDX_BOOKING_GUEST ON BOOKINGS(GUEST_ID);
CREATE INDEX IDX_BOOKING_ROOM ON BOOKINGS(ROOM_ID);
CREATE INDEX IDX_BOOKING_STATUS ON BOOKINGS(BOOKING_STATUS);
CREATE INDEX IDX_BOOKING_DATES ON BOOKINGS(CHECK_IN_DATE, CHECK_OUT_DATE);
CREATE INDEX IDX_PAYMENT_BOOKING ON PAYMENTS(BOOKING_ID);
CREATE INDEX IDX_USER_USERNAME ON USERS(USERNAME);
CREATE INDEX IDX_USER_EMAIL ON USERS(EMAIL);

-- Insert default admin user (password: Admin123!)
INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, ENABLED)
VALUES (USER_SEQ.NEXTVAL, 'admin', 'admin@hotel.com', 
        '$2a$10$M8KJkL9xPqNnE2WrFgHjKqLmNoPqRsTuVwXyZ1234567890ABCDEF', 
        'Admin', 'User', '1');

INSERT INTO USER_ROLES (USER_ID, ROLE) 
SELECT ID, 'ADMIN' FROM USERS WHERE USERNAME = 'admin';

-- Insert sample rooms
INSERT INTO ROOMS (ID, ROOM_NUMBER, ROOM_TYPE, PRICE_PER_NIGHT, CAPACITY, DESCRIPTION, FLOOR_NUMBER, HAS_VIEW)
VALUES (ROOM_SEQ.NEXTVAL, '101', 'DELUXE', 250.00, 2, 'Luxury room with ocean view', 1, '1');

INSERT INTO ROOMS (ID, ROOM_NUMBER, ROOM_TYPE, PRICE_PER_NIGHT, CAPACITY, DESCRIPTION, FLOOR_NUMBER, HAS_VIEW)
VALUES (ROOM_SEQ.NEXTVAL, '102', 'STANDARD', 150.00, 2, 'Comfortable room with city view', 1, '0');

INSERT INTO ROOMS (ID, ROOM_NUMBER, ROOM_TYPE, PRICE_PER_NIGHT, CAPACITY, DESCRIPTION, FLOOR_NUMBER, HAS_VIEW)
VALUES (ROOM_SEQ.NEXTVAL, '201', 'SUITE', 400.00, 4, 'Spacious suite with sea view and living area', 2, '1');

-- Insert sample guests
INSERT INTO GUESTS (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY, IS_VIP)
VALUES (GUEST_SEQ.NEXTVAL, 'John', 'Doe', 'john.doe@email.com', '+1234567890', '123 Main St', 'New York', 'USA', '1');

INSERT INTO GUESTS (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY, IS_VIP)
VALUES (GUEST_SEQ.NEXTVAL, 'Jane', 'Smith', 'jane.smith@email.com', '+9876543210', '456 Oak Ave', 'Los Angeles', 'USA', '0');

COMMIT;